### PR TITLE
Dean/package manage with poetry

### PR DESCRIPTION
**Pull request by deanputney**
This change manages required packages and Python version using [Poetry](https://python-poetry.org/). The reasons I'm suggesting this change are:

* Fully automates package installation.
* Installs the correct version of Python for this project.
* Keeps everything inside a virtual environment just for this project, avoiding conflicts with other projects.

This doesn't prevent a user from running the script on their local installation, if they desire.

Give it a try, let me know what you think!

### CODE REVIEW

**Comment by easlice** [comment]
Hey, thanks for the PR!

This looks pretty good. Following the instructions on my local system work, so that seems good.

How about leaving both sets of instructions in the README, one for non-poetry installs and one for using poetry? I know if I had come across this before, not knowing what poetry was, I would have seen this and assumed it was necessary, which would make me skip by using it, since I don't normally use poetry and wouldn't install it for a one off script like this.

You can decide the verbiage, or I can do it after merging the PR, doesn't matter to me, I just want it clear that poetry isn't necessary to run it.

**Comment by deanputney** [comment]
In the case that you want to support running this directly as well, I would recommend that we add a `requirements.txt` so that the packages can be installed automatically with `pip install -r requirements.txt`. I've added that as well as a description to the README.

**Comment by easlice** [comment]
Agreed about the `requirements.txt`. And the contributing section is a nice touch.

And I appreciate the help from someone who seems to work more professionally in python than I do.

I'm going to resolve the conflict from my known issues section, merge this in, then tweak it a bit.

**Comment by deanputney** [comment]
Happy to help! Nice to get a clean PR in every once in a while 🧼

**Pull request merged**
